<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Property;
use App\Models\User;

class PropertySeeder extends Seeder
{
    public function run()
    {
        $user = User::first();

        if (!$user) {
            $this->command->error('No hay usuarios. Crea uno primero.');
            return;
        }

        $properties = [
            [
                'title' => 'Departamento Amueblado Centro Histórico',
                'description' => 'Hermoso departamento completamente amueblado en pleno centro histórico. A pasos de la Catedral y Teatro Degollado. Ideal para profesionistas o estudiantes. Incluye servicios de agua y gas.',
                'address' => 'Calle Morelos 345',
                'city' => 'Guadalajara',
                'state' => 'Jalisco',
                'country' => 'México',
                'postal_code' => '44100',
                'price' => 8500.00,
                'bedrooms' => 2,
                'bathrooms' => 1,
                'area' => 65.00,
                'type' => 'departamento',
                'is_active' => true,
                'user_id' => $user->id,
                'latitude' => 20.6767,
                'longitude' => -103.3475,
            ],
            [
                'title' => 'Casa Colonial Zona Centro',
                'description' => 'Preciosa casa colonial restaurada. Techos altos, pisos originales, patio central con fuente. Perfecta para familias. Cerca de mercados, parques y transporte público.',
                'address' => 'Calle Independencia 789',
                'city' => 'Guadalajara',
                'state' => 'Jalisco',
                'country' => 'México',
                'postal_code' => '44100',
                'price' => 15000.00,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'area' => 180.00,
                'type' => 'casa',
                'is_active' => true,
                'user_id' => $user->id,
                'latitude' => 20.6756,
                'longitude' => -103.3458,
            ],
            [
                'title' => 'Estudio Moderno cerca de Revolución',
                'description' => 'Estudio tipo loft, recién remodelado. Espacio abierto con cocina integrada, baño completo. Edificio con seguridad 24/7. Internet de alta velocidad incluido.',
                'address' => 'Av. Revolución 234',
                'city' => 'Guadalajara',
                'state' => 'Jalisco',
                'country' => 'México',
                'postal_code' => '44100',
                'price' => 6500.00,
                'bedrooms' => 1,
                'bathrooms' => 1,
                'area' => 40.00,
                'type' => 'estudio',
                'is_active' => true,
                'user_id' => $user->id,
                'latitude' => 20.6745,
                'longitude' => -103.3490,
            ],
            [
                'title' => 'Departamento Familiar San Juan Bosco',
                'description' => 'Amplio departamento en segundo piso. 3 recámaras con closet, sala-comedor espaciosa. Estacionamiento techado. Cerca de escuelas y supermercados.',
                'address' => 'Calle San Felipe 567',
                'city' => 'Guadalajara',
                'state' => 'Jalisco',
                'country' => 'México',
                'postal_code' => '44100',
                'price' => 12000.00,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'area' => 110.00,
                'type' => 'departamento',
                'is_active' => true,
                'user_id' => $user->id,
                'latitude' => 20.6778,
                'longitude' => -103.3442,
            ],
            [
                'title' => 'Loft Industrial Tlaquepaque Centro',
                'description' => 'Loft estilo industrial en edificio restaurado. Ventanales amplios, cocina equipada, baño moderno. Perfecto para creativos y emprendedores. Pet friendly.',
                'address' => 'Av. Niños Héroes 123',
                'city' => 'Guadalajara',
                'state' => 'Jalisco',
                'country' => 'México',
                'postal_code' => '44100',
                'price' => 9800.00,
                'bedrooms' => 1,
                'bathrooms' => 1,
                'area' => 75.00,
                'type' => 'loft',
                'is_active' => true,
                'user_id' => $user->id,
                'latitude' => 20.6734,
                'longitude' => -103.3510,
            ],
            [
                'title' => 'Casa Compartida para Estudiantes',
                'description' => 'Casa grande con 4 habitaciones individuales. Áreas comunes: cocina, sala, comedor, patio. Renta por habitación. Ambiente tranquilo y seguro.',
                'address' => 'Calle Libertad 890',
                'city' => 'Guadalajara',
                'state' => 'Jalisco',
                'country' => 'México',
                'postal_code' => '44100',
                'price' => 4500.00,
                'bedrooms' => 4,
                'bathrooms' => 2,
                'area' => 200.00,
                'type' => 'casa',
                'is_active' => true,
                'user_id' => $user->id,
                'latitude' => 20.6789,
                'longitude' => -103.3465,
            ],
            [
                'title' => 'Penthouse Vista Panorámica Centro',
                'description' => 'Exclusivo penthouse con terraza privada y vista 360° del centro. Acabados de lujo, 2 niveles, cocina gourmet. Estacionamiento para 2 autos.',
                'address' => 'Av. Juárez 456',
                'city' => 'Guadalajara',
                'state' => 'Jalisco',
                'country' => 'México',
                'postal_code' => '44100',
                'price' => 25000.00,
                'bedrooms' => 3,
                'bathrooms' => 3,
                'area' => 220.00,
                'type' => 'penthouse',
                'is_active' => true,
                'user_id' => $user->id,
                'latitude' => 20.6723,
                'longitude' => -103.3498,
            ],
            [
                'title' => 'Departamento Ejecutivo Amueblado',
                'description' => 'Departamento ideal para ejecutivos. Totalmente equipado: muebles, electrodomésticos, ropa de cama. Servicios incluidos. Contrato flexible.',
                'address' => 'Calle Prisciliano Sánchez 678',
                'city' => 'Guadalajara',
                'state' => 'Jalisco',
                'country' => 'México',
                'postal_code' => '44100',
                'price' => 11500.00,
                'bedrooms' => 2,
                'bathrooms' => 1,
                'area' => 80.00,
                'type' => 'departamento',
                'is_active' => true,
                'user_id' => $user->id,
                'latitude' => 20.6801,
                'longitude' => -103.3430,
            ],
            [
                'title' => 'Casa con Patio Grande Zona Revolución',
                'description' => 'Casa tradicional con amplio patio trasero. Ideal para mascotas. 2 recámaras, sala, comedor, cocina integral. Zona tranquila y céntrica.',
                'address' => 'Calle Reforma 234',
                'city' => 'Guadalajara',
                'state' => 'Jalisco',
                'country' => 'México',
                'postal_code' => '44100',
                'price' => 10500.00,
                'bedrooms' => 2,
                'bathrooms' => 1,
                'area' => 120.00,
                'type' => 'casa',
                'is_active' => true,
                'user_id' => $user->id,
                'latitude' => 20.6750,
                'longitude' => -103.3482,
            ],
            [
                'title' => 'Mini Departamento Económico',
                'description' => 'Departamento compacto pero funcional. Cocineta, baño completo. Perfecto para una persona. Agua incluida. Cerca de todo.',
                'address' => 'Calle Medrano 901',
                'city' => 'Guadalajara',
                'state' => 'Jalisco',
                'country' => 'México',
                'postal_code' => '44100',
                'price' => 4800.00,
                'bedrooms' => 1,
                'bathrooms' => 1,
                'area' => 35.00,
                'type' => 'departamento',
                'is_active' => true,
                'user_id' => $user->id,
                'latitude' => 20.6770,
                'longitude' => -103.3520,
            ],
            [
                'title' => 'Departamento con Balcón Av. Federalismo',
                'description' => 'Departamento luminoso con balcón amplio. Vista a la avenida. 2 recámaras, cocina equipada, closets. Excelente ubicación con acceso a transporte.',
                'address' => 'Av. Federalismo 1122',
                'city' => 'Guadalajara',
                'state' => 'Jalisco',
                'country' => 'México',
                'postal_code' => '44100',
                'price' => 9200.00,
                'bedrooms' => 2,
                'bathrooms' => 1,
                'area' => 70.00,
                'type' => 'departamento',
                'is_active' => true,
                'user_id' => $user->id,
                'latitude' => 20.6742,
                'longitude' => -103.3468,
            ],
            [
                'title' => 'Casa Remodelada Colonia Centro',
                'description' => 'Casa totalmente remodelada. Acabados modernos, cocina nueva, 3 baños completos. Cochera para 2 autos. Jardín pequeño. Lista para habitar.',
                'address' => 'Calle Hidalgo 432',
                'city' => 'Guadalajara',
                'state' => 'Jalisco',
                'country' => 'México',
                'postal_code' => '44100',
                'price' => 18500.00,
                'bedrooms' => 4,
                'bathrooms' => 3,
                'area' => 200.00,
                'type' => 'casa',
                'is_active' => true,
                'user_id' => $user->id,
                'latitude' => 20.6785,
                'longitude' => -103.3455,
            ],
            [
                'title' => 'Estudio Frente a Parque Morelos',
                'description' => 'Estudio con vista al Parque Morelos. Ambiente tranquilo y verde. Cocina integral, baño moderno. Ideal para persona sola o pareja joven.',
                'address' => 'Calle Colón 156',
                'city' => 'Guadalajara',
                'state' => 'Jalisco',
                'country' => 'México',
                'postal_code' => '44100',
                'price' => 7200.00,
                'bedrooms' => 1,
                'bathrooms' => 1,
                'area' => 45.00,
                'type' => 'estudio',
                'is_active' => true,
                'user_id' => $user->id,
                'latitude' => 20.6795,
                'longitude' => -103.3438,
            ],
            [
                'title' => 'Departamento en Edificio Histórico',
                'description' => 'Departamento en edificio de los años 40 restaurado. Pisos de madera, ventanas altas. Mantenimiento incluido. Ambiente bohemio y cultural.',
                'address' => 'Calle Pedro Moreno 678',
                'city' => 'Guadalajara',
                'state' => 'Jalisco',
                'country' => 'México',
                'postal_code' => '44100',
                'price' => 8900.00,
                'bedrooms' => 2,
                'bathrooms' => 1,
                'area' => 85.00,
                'type' => 'departamento',
                'is_active' => true,
                'user_id' => $user->id,
                'latitude' => 20.6738,
                'longitude' => -103.3502,
            ],
            [
                'title' => 'Casa con Roof Garden Centro',
                'description' => 'Casa de 3 niveles con roof garden privado. Vista espectacular. Estacionamiento, 3 recámaras, sala de TV. Perfecta para familia moderna.',
                'address' => 'Calle Maestranza 290',
                'city' => 'Guadalajara',
                'state' => 'Jalisco',
                'country' => 'México',
                'postal_code' => '44100',
                'price' => 22000.00,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'area' => 190.00,
                'type' => 'casa',
                'is_active' => true,
                'user_id' => $user->id,
                'latitude' => 20.6763,
                'longitude' => -103.3448,
            ],
            [
                'title' => 'Loft Minimalista Zona Revolución',
                'description' => 'Loft de diseño minimalista. Doble altura, mucha luz natural. Cocina italiana, closet vestidor. Edificio boutique con gym.',
                'address' => 'Av. Revolución 567',
                'city' => 'Guadalajara',
                'state' => 'Jalisco',
                'country' => 'México',
                'postal_code' => '44100',
                'price' => 14500.00,
                'bedrooms' => 2,
                'bathrooms' => 2,
                'area' => 95.00,
                'type' => 'loft',
                'is_active' => true,
                'user_id' => $user->id,
                'latitude' => 20.6752,
                'longitude' => -103.3478,
            ],
            [
                'title' => 'Departamento Cerca CUCSH',
                'description' => 'Departamento ideal para estudiantes universitarios. Cerca del Centro Universitario de Ciencias Sociales. 2 recámaras, amueblado básico disponible.',
                'address' => 'Calle Belisario Domínguez 823',
                'city' => 'Guadalajara',
                'state' => 'Jalisco',
                'country' => 'México',
                'postal_code' => '44100',
                'price' => 6800.00,
                'bedrooms' => 2,
                'bathrooms' => 1,
                'area' => 55.00,
                'type' => 'departamento',
                'is_active' => true,
                'user_id' => $user->id,
                'latitude' => 20.6810,
                'longitude' => -103.3425,
            ],
            [
                'title' => 'Casa Tradicional con Traspatio',
                'description' => 'Casa tradicional tapatía. Patio interior y traspatio amplio. 2 plantas, 3 recámaras. Zona muy tranquila. Ideal para familia o profesionistas.',
                'address' => 'Calle Contreras Medellín 445',
                'city' => 'Guadalajara',
                'state' => 'Jalisco',
                'country' => 'México',
                'postal_code' => '44100',
                'price' => 13500.00,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'area' => 160.00,
                'type' => 'casa',
                'is_active' => true,
                'user_id' => $user->id,
                'latitude' => 20.6728,
                'longitude' => -103.3515,
            ],
            [
                'title' => 'Departamento Dúplex Moderno',
                'description' => 'Departamento tipo dúplex en último piso. Recámaras en planta alta, sala-comedor-cocina abajo. Terraza privada. Edificio nuevo con elevador.',
                'address' => 'Calle Galeana 189',
                'city' => 'Guadalajara',
                'state' => 'Jalisco',
                'country' => 'México',
                'postal_code' => '44100',
                'price' => 16500.00,
                'bedrooms' => 2,
                'bathrooms' => 2,
                'area' => 105.00,
                'type' => 'departamento',
                'is_active' => true,
                'user_id' => $user->id,
                'latitude' => 20.6772,
                'longitude' => -103.3492,
            ],
            [
                'title' => 'Habitación Amueblada Centro',
                'description' => 'Habitación privada en casa compartida. Baño compartido. Incluye muebles, internet, servicios. Ambiente respetuoso. Solo mujeres.',
                'address' => 'Calle López Cotilla 734',
                'city' => 'Guadalajara',
                'state' => 'Jalisco',
                'country' => 'México',
                'postal_code' => '44100',
                'price' => 3500.00,
                'bedrooms' => 1,
                'bathrooms' => 1,
                'area' => 25.00,
                'type' => 'habitacion',
                'is_active' => true,
                'user_id' => $user->id,
                'latitude' => 20.6758,
                'longitude' => -103.3462,
            ],
        ];

        foreach ($properties as $propertyData) {
            Property::create($propertyData);
        }

        $this->command->info('✓ 20 propiedades de renta creadas en zona Revolución, Guadalajara Centro');
    }
}
